### ISSUE TITLE
[BUG]mapped shift-TAB while it was already used by shadertoy

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#124]
The new keyword autocompletion is mapped on shift-TAB.

Alas,  shift-TAB was already used by a shadertoy feature I use frequently: realign indentation in a whole region + replace tabs by spaces.

→ please use another key binding !
For instance shift-SPACE might be appropriate, for after all we already often type a space after a keyword,
plus it would help avoiding not compilable invisible characters like "half-space" or "insecable space" often binded to modifier-SPACE.

**Comment by Boscop** [comment]
Yes, the fact that Shift+Tab opens this autocompletion menu is very annoying.
Autocompletion should be Ctrl+m or Ctrl+Space.
Most editors use Tab for indent and Shift+Tab for unindent.
And today iq implemented Shift+Tab to cause unindent as well on Shadertoy.
But this extension prevents it from working because its key handler gets run first.
So please don't override Shfit+Tab and let us use it for unindent :)

**Comment by EthanLowenthal** [comment]
Didn't realize it was already used --  I will change it to Ctrl+m -- originally it was tab, with a lot of logic to see if it was code-completion or indent, but I was afraid I was going to break something.
