### ISSUE TITLE
Download wav file from sound buffer

### ISSUE THREAD

**Issue by patuwwy** [patuwwy/ShaderToy-Chrome-Plugin#31]

**Comment by ttoinou** [comment]
I have a first draft working in another extension fork https://github.com/ttoinou/shadertoy-frame-exporter
Looks like I'm limited by the texture size so I'll need to render the WAV block by block. And since Chrome will need to hold all audio samples in memory, not sure I can allocate a big enough buffer, so maybe I'll need to download multiple .wav files and concatenate them with ffmpeg afterwards manually (but can generate command line automatically)

**Comment by patuwwy** [comment]
@ttoinou iq just announced that export to wave will be soon available on ShaderToy.

**Comment by ttoinou** [comment]
yeah.... :'(

**Comment by ttoinou** [comment]
I mean, that's good news, just lost so much time
