### ISSUE TITLE
Open recent

### ISSUE THREAD

**Issue by patuwwy** [patuwwy/ShaderToy-Chrome-Plugin#66]
A list of the 5 things you have been working on recently that allow you to quickly return to coding without having to search for a specific shader in the collection.

**Comment by FabriceNeyret** [comment]
including the draft shaders ? (something that is (un)managed castrophically by shadertoy for now since when you relaunch the browser and got disconnected, all the draft unlisted shaders are redirected to error.html so that you loose the right shader IDs you were working on, lost within the jungle of all your past shaders and not even having a date to sort).

how do we access this feature ?

**Comment by patuwwy** [comment]
The idea is to collect the IDs of the shaders you visit and you have the right to edit them (i.e. you own them). Their status is not significant.
The ID list will be saved in your browser and displayed in an always accessible place.
The list will contain a thumbnail and, if possible, a title.

**Comment by patuwwy** [comment]
#69
